(self.AMP=self.AMP||[]).push({n:"amp-lightbox",v:"1810052256480",f:(function(AMP,_){
var f;function l(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]}function m(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var aa=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function n(a){var b=Object.create(null);if(!a)return b;for(var c;c=aa.exec(a);){var d=m(c[1],c[1]),e=c[2]?m(c[2],c[2]):"";b[d]=e}return b};var p="";
function t(a){var b=a||self,c;if(b.AMP_MODE)c=b.AMP_MODE;else{c=b;var d=!!(self.AMP_CONFIG||{}).test||!1,e=n(c.location.originalHash||c.location.hash),g=n(c.location.search);p||(p=c.AMP_CONFIG&&c.AMP_CONFIG.v?c.AMP_CONFIG.v:"011810052256480");c=b.AMP_MODE={localDev:!1,development:!("1"!=e.development&&!c.AMP_DEV_MODE),examiner:"2"==e.development,filter:e.filter,geoOverride:e["amp-geo"],minified:!0,lite:void 0!=g.amp_lite,test:d,log:e.log,version:"1810052256480",rtvVersion:p}}return c};self.log=self.log||{user:null,dev:null,userForEmbed:null};var u=self.log;var ba=Object.prototype.hasOwnProperty;function v(){var a,b=Object.create(null);a&&Object.assign(b,a);return b}function w(a){return a||{}};function x(a,b){a=a.__AMP_TOP||a;return y(a,b)}function z(a){var b=A(a),b=B(b);return y(b,"history")}function C(a,b){a=A(a);a=B(a);return y(a,b)}function A(a){return a.nodeType?x((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function B(a){a=A(a);return a.isSingleDoc()?a.win:a}function y(a,b){D(a,b);var c=a.services;c||(c=a.services={});var d=c;a=d[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}
function D(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function ca(a){a.parentElement&&a.parentElement.removeChild(a)}function da(a,b){for(var c,d=a;d&&d!==c;d=d.parentElement)if(b(d))return d;return null}function E(a){return a.closest?a.closest(".i-amphtml-fie"):da(a,function(a){var b=a.matches||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector;return b?b.call(a,".i-amphtml-fie"):!1})};var F;function ea(a,b){var c=void 0,d=a,e=b,g;g=function(a){try{return e(a)}catch(r){throw self.reportError(r),r;}};var h=fa(),k=!1;c&&(k=c.capture);d.addEventListener("click",g,h?c:k);return function(){d&&d.removeEventListener("click",g,h?c:k);g=d=e=null}}function fa(){if(void 0!==F)return F;F=!1;try{var a={get capture(){F=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(b){}return F};function ga(a,b){var c=b,d=ea(a,function(a){try{c(a)}finally{c=null,d()}})};var G,H="Webkit webkit Moz moz ms O o".split(" ");function I(a,b,c){if(2>b.length?0:0==b.lastIndexOf("--",0))return b;G||(G=v());var d=G[b];if(!d||c){d=b;if(void 0===a[b]){var e=b.charAt(0).toUpperCase()+b.slice(1);a:{for(var g=0;g<H.length;g++){var h=H[g]+e;if(void 0!==a[h]){e=h;break a}}e=""}var k=e;void 0!==a[k]&&(d=k)}c||(G[b]=d)}return d}function J(a,b){a=a.style;for(var c in b)a.setProperty(I(a,c),b[c].toString(),"important")}
function K(a,b,c){var d;(b=I(a.style,b,void 0))&&(a.style[b]=d?c+d:c)}function L(a,b){for(var c in b)K(a,c,b[c])}function M(a){if("display"in a){var b;if(u.dev)b=u.dev;else throw Error("failed to call initLogConstructor");b.error("STYLE","`display` style detected in styles. You must use toggle instead.")}return a}function ha(a){var b=!0;void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")}
function ia(a){for(var b=["transition"],c=0;c<b.length;c++)K(a,b[c],null)};function N(){this.l=null}f=N.prototype;f.add=function(a){var b=this;this.l||(this.l=[]);this.l.push(a);return function(){b.remove(a)}};f.remove=function(a){this.l&&(a=this.l.indexOf(a),-1<a&&this.l.splice(a,1))};f.removeAll=function(){this.l&&(this.l.length=0)};f.fire=function(a){if(this.l)for(var b=this.l,c=0;c<b.length;c++)(0,b[c])(a)};f.getHandlerCount=function(){return this.l?this.l.length:0};function ja(a,b){function c(){d=0;var h=500-(a.Date.now()-e);if(0<h)d=a.setTimeout(c,h);else{var k=g;g=null;b.apply(null,k)}}var d=0,e=0,g=null;return function(b){for(var k=[],h=0;h<arguments.length;++h)k[h-0]=arguments[h];e=a.Date.now();g=k;d||(d=a.setTimeout(c,500))}};function ka(a,b){for(var c=0;c<a.length;c++)if(b(a[c],c,a))return c;return-1};var O;function la(a){a=a.ownerDocument||a;O&&O.ownerDocument===a||(O=a.createElement("div"));return ma}function ma(a){O.innerHTML=a[0];var b=O.firstElementChild;O.removeChild(b);return b};function P(a,b,c){var d=this;this.sa=x(a,"timer");this.wa=b;this.va=c||0;this.L=-1;this.aa=0;this.fa=!1;this.ta=function(){return d.U()}}P.prototype.isPending=function(){return-1!=this.L};P.prototype.schedule=function(a){var b=a||this.va;this.fa&&10>b&&(b=10);var c=Date.now()+b;return!this.isPending()||-10>c-this.aa?(this.cancel(),this.aa=c,this.L=this.sa.delay(this.ta,b),!0):!1};P.prototype.U=function(){this.L=-1;this.aa=0;this.fa=!0;this.wa();this.fa=!1};
P.prototype.cancel=function(){this.isPending()&&(this.sa.cancel(this.L),this.L=-1)};function na(a,b,c){var d=Date.now();this.type=a;this.data=b;this.time=d;this.event=c}
function Q(a,b){this.w=a;this.c=[];this.H=[];this.m=[];this.h=[];this.j=null;this.Ba=b;this.W=!1;this.U=new P(a.ownerDocument.defaultView,this.na.bind(this));this.pa=new N;this.K=Object.create(null);this.ma=this.Aa.bind(this);this.ka=this.ya.bind(this);this.la=this.za.bind(this);this.ja=this.xa.bind(this);this.w.addEventListener("touchstart",this.ma);this.w.addEventListener("touchend",this.ka);this.w.addEventListener("touchmove",this.la);this.w.addEventListener("touchcancel",this.ja);this.ba=!1}
function oa(a){var b;b=void 0===b?!1:b;var c=a.__AMP_Gestures;c||(c=new Q(a,b),a.__AMP_Gestures=c);return c}f=Q.prototype;f.cleanup=function(){this.w.removeEventListener("touchstart",this.ma);this.w.removeEventListener("touchend",this.ka);this.w.removeEventListener("touchmove",this.la);this.w.removeEventListener("touchcancel",this.ja);delete this.w.__AMP_Gestures;this.U.cancel()};f.onGesture=function(a,b){var c=new a(this),d=c.getType(),e=this.K[d];e||(this.c.push(c),e=new N,this.K[d]=e);return e.add(b)};
f.removeGesture=function(a){var b=(new a(this)).getType();if(a=this.K[b]){a.removeAll();a=ka(this.c,function(a){return a.getType()==b});if(0>a)return!1;this.c.splice(a,1);this.m.splice(a,1);this.h.splice(a,1);this.H.splice(a,1);delete this.K[b];return!0}return!1};f.onPointerDown=function(a){return this.pa.add(a)};
f.Aa=function(a){var b=Date.now();this.W=!1;this.pa.fire(a);for(var c=0;c<this.c.length;c++)if(!this.m[c]&&(this.h[c]&&this.h[c]<b&&R(this,c),this.c[c].onTouchStart(a))){var d=c;this.H[d]=!0;this.h[d]=0}S(this,a)};f.za=function(a){for(var b=Date.now(),c=0;c<this.c.length;c++)this.H[c]&&(this.h[c]&&this.h[c]<b?R(this,c):this.c[c].onTouchMove(a)||R(this,c));S(this,a)};
f.ya=function(a){for(var b=Date.now(),c=0;c<this.c.length;c++)this.H[c]&&(this.h[c]&&this.h[c]<b?R(this,c):(this.c[c].onTouchEnd(a),(!this.h[c]||this.h[c]<b)&&R(this,c)));S(this,a)};f.xa=function(a){for(var b=0;b<this.c.length;b++){var c=b;this.m[c]=0;R(this,c)}S(this,a)};function S(a,b){var c=!!a.j||a.W;a.W=!1;if(!c)for(var d=Date.now(),e=0;e<a.c.length;e++)if(a.m[e]||a.h[e]&&a.h[e]>=d){c=!0;break}c&&(b.stopPropagation(),a.Ba||b.preventDefault());a.ba&&(a.ba=!1,a.na())}
f.na=function(){for(var a=Date.now(),b=-1,c=0;c<this.c.length;c++)if(!this.m[c])this.h[c]&&this.h[c]<a&&R(this,c);else if(-1==b||this.m[c]>this.m[b])b=c;if(-1!=b){for(var d=0,c=0;c<this.c.length;c++)!this.m[c]&&this.H[c]&&(d=Math.max(d,this.h[c]-a));if(2>d){for(var a=b,c=this.c[a],e=0;e<this.c.length;e++)if(e!=a){var g=e;this.m[g]=0;R(this,g)}this.m[a]=0;this.h[a]=0;this.j=c;c.acceptStart()}else this.U.schedule(d)}};function R(a,b){a.H[b]=!1;a.h[b]=0;a.m[b]||a.c[b].acceptCancel()}
function T(a,b){this.Ca=a;this.T=b}f=T.prototype;f.getType=function(){return this.Ca};f.signalReady=function(a){var b=this.T;if(b.j)this.acceptCancel();else{for(var c=Date.now(),d=0;d<b.c.length;d++)b.c[d]==this&&(b.m[d]=c+a,b.h[d]=0);b.ba=!0}};f.signalPending=function(a){var b=this.T;if(b.j)this.acceptCancel();else for(var c=Date.now(),d=0;d<b.c.length;d++)b.c[d]==this&&(b.h[d]=c+a)};f.signalEnd=function(){var a=this.T;a.j==this&&(a.j=null,a.W=!0)};
f.signalEmit=function(a,b){var c=this.T.K[this.getType()];c&&c.fire(new na(this.getType(),a,b))};f.acceptStart=function(){};f.acceptCancel=function(){};f.onTouchStart=function(){return!1};f.onTouchMove=function(){return!1};f.onTouchEnd=function(){};function U(a,b,c){1>b&&(b=1);var d=a/b,e=.5+Math.min(b/33.34,.5);return d*e+c*(1-e)};function V(a,b,c,d){T.call(this,a,b);this.R=c;this.V=d;this.j=!1;this.J=this.I=this.ca=this.S=this.ra=this.ea=this.da=this.D=this.C=this.G=this.F=0}l(V,T);f=V.prototype;f.onTouchStart=function(a){return(a=a.touches)&&1==a.length?(this.ra=Date.now(),this.F=a[0].clientX,this.G=a[0].clientY,!0):!1};
f.onTouchMove=function(a){var b=a.touches;if(b&&1==b.length){var c=b[0],b=c.clientX,c=c.clientY;this.C=b;this.D=c;if(this.j)W(this,!1,!1,a);else if(a=Math.abs(b-this.F),b=Math.abs(c-this.G),this.R&&this.V)(8<=a||8<=b)&&this.signalReady(-10);else if(this.R)if(8<=a&&a>b)this.signalReady(-10);else{if(8<=b)return!1}else if(this.V)if(8<=b&&b>a)this.signalReady(-10);else{if(8<=a)return!1}else return!1;return!0}return!1};f.onTouchEnd=function(a){this.j&&(this.j=!1,W(this,!1,!0,a),this.signalEnd())};
f.acceptStart=function(){this.j=!0;this.da=this.F;this.ea=this.G;this.ca=this.ra;this.F=this.C;this.G=this.D;W(this,!0,!1,null)};f.acceptCancel=function(){this.j=!1};
function W(a,b,c,d){a.S=Date.now();var e=a.S-a.ca;if(!c&&4<e||c&&16<e)a.I=U(a.C-a.da,e,a.I),a.J=U(a.D-a.ea,e,a.J),a.I=1E-4<Math.abs(a.I)?a.I:0,a.J=1E-4<Math.abs(a.J)?a.J:0,a.da=a.C,a.ea=a.D,a.ca=a.S;a.signalEmit({first:b,last:c,time:a.S,deltaX:a.R?a.C-a.F:0,deltaY:a.V?a.D-a.G:0,startX:a.F,startY:a.G,lastX:a.C,lastY:a.D,velocityX:a.R?a.I:0,velocityY:a.V?a.J:0},d)}function pa(a){V.call(this,"swipe-xy",a,!0,!0)}l(pa,V);var qa=['\n    <i-amphtml-ad-close-header role=button tabindex=0 aria-label="Close Ad">\n      <div>Ad</div>\n      <i-amphtml-ad-close-button class="amp-ad-close-button">\n      </i-amphtml-ad-close-button>\n    </i-amphtml-ad-close-header>'];qa.raw=['\n    <i-amphtml-ad-close-header role=button tabindex=0 aria-label="Close Ad">\n      <div>Ad</div>\n      <i-amphtml-ad-close-button class="amp-ad-close-button">\n      </i-amphtml-ad-close-button>\n    </i-amphtml-ad-close-header>'];
var X={"fade-in":{openStyle:w({opacity:1}),closedStyle:w({opacity:0}),durationSeconds:.1},"fly-in-bottom":{openStyle:w({transform:"translate(0, 0)"}),closedStyle:w({transform:"translate(0, 100%)"}),durationSeconds:.2},"fly-in-top":{openStyle:w({transform:"translate(0, 0)"}),closedStyle:w({transform:"translate(0, -100%)"}),durationSeconds:.2}};
function Y(a){var b;b=AMP.BaseElement.call(this,a)||this;b.ha=null;b.o=null;b.ia=null;b.Y=null;b.$=-1;b.M=!1;b.O=null;b.B=!1;b.A=0;b.oa=0;b.Z=0;b.ga=null;b.N=(a.getAttribute("animate-in")||"fade-in").toLowerCase();b.P=null;b.X=ja(b.win,function(){var a=b.o;b.scheduleLayout(a);b.scheduleResume(a)});return b}l(Y,AMP.BaseElement);f=Y.prototype;
f.buildCallback=function(){this.user().assert(ba.call(X,this.N),"Invalid `animate-in` value %s",this.N);this.element.classList.add("i-amphtml-overlay");var a;a:{a=this.element;if(a.nodeType){var b=(a.ownerDocument||a).defaultView;if(b=b!=(b.__AMP_TOP||b)&&D(b,"action")?y(b,"action"):null){a=b;break a}}a=C(a,"action")}this.ia=a;a=this.win;E(this.element)&&ra(a,a.document.body);this.registerAction("open",this.activate.bind(this));this.registerAction("close",this.close.bind(this))};
function sa(a){ta(a,!0).forEach(function(b){a.setAsOwner(b)})}function ta(a,b){if(!a.Y||b){var c;if(c=a.element.getElementsByClassName("i-amphtml-element")){for(var d=Array(c.length),e=0;e<c.length;e++)d[e]=c[e];c=d}else c=[];a.Y=c}return a.Y}
function ua(a){if(!a.o){var b=a.element;a.B=b.hasAttribute("scrollable");var c=a.getRealChildren();a.o=b.ownerDocument.createElement("div");a.B||a.applyFillContent(a.o);b.appendChild(a.o);c.forEach(function(b){a.o.appendChild(b)});a.B&&(sa(a),b.classList.add("i-amphtml-scrollable"),b.addEventListener("amp:dom-update",function(){sa(a);Z(a,a.A,a.A)}),b.addEventListener("scroll",a.qa.bind(a)));if(!a.B){var d=oa(b);d.onGesture(pa,function(){})}}}f.layoutCallback=function(){return Promise.resolve()};
f.activate=function(){var a=this;this.M||(ua(this),this.O=this.ua.bind(this),this.win.document.documentElement.addEventListener("keydown",this.O),this.getViewport().enterLightboxMode(this.element).then(function(){return va(a)}))};f.mutatedAttributesCallback=function(a){var b=a.open;void 0!==b&&(b?this.activate():this.close())};function wa(a){var b=a.o.querySelector("[autofocus]");if(b)try{b.focus()}catch(c){}}
function va(a){var b=a.element,c=X[a.N],d=c.durationSeconds,e=c.openStyle,g=c.closedStyle,h=Object.keys(e).map(function(a){return a+" "+d+"s ease-in"}).join(",");a.Z++;a.B&&K(b,"webkitOverflowScrolling","touch");K(b,"transition",h);L(b,M(g));ha(b);a.mutateElement(function(){b.scrollTop=0});wa(a);xa(a);a.mutateElement(function(){L(b,M(e))});c=a.o;a.B?(a.qa(),Z(a,a.A,a.A)):a.updateInViewport(c,!0);b.addEventListener("transitionend",a.X);b.addEventListener("animationend",a.X);a.scheduleLayout(c);a.scheduleResume(c);
ya(a,"lightboxOpen");z(a.getAmpDoc()).push(a.close.bind(a)).then(function(b){a.$=b});a.M=!0}function xa(a){var b=a.element;if(null!=b.getAttribute("close-button")){var c=la(b)(qa);a.P=c;ga(c,function(){return a.close()});b.insertBefore(c,a.o);var d;a.measureMutateElement(function(){d=c.getBoundingClientRect().height},function(){c.classList.add("amp-ad-close-header");J(a.o,{"margin-top":d+"px","min-height":"calc(100vh - "+(d+"px")+")"})})}}f.ua=function(a){27==a.keyCode&&this.close()};
f.close=function(){var a=this;this.M&&(this.B&&K(this.element,"webkitOverflowScrolling",""),this.P&&(ca(this.P),this.P=null),this.getViewport().leaveLightboxMode(this.element).then(function(){return za(a)}))};
function za(a){function b(){d==a.Z&&(a.collapse(),a.X())}var c=a.element,d=++a.Z;Aa(a)?(ia(c),b()):(c.addEventListener("transitionend",b),c.addEventListener("animationend",b));L(c,M(X[a.N].closedStyle));-1!=a.$&&z(a.getAmpDoc()).pop(a.$);a.win.document.documentElement.removeEventListener("keydown",a.O);a.O=null;a.schedulePause(a.o);a.M=!1;ya(a,"lightboxClose")}function Aa(a){return"inabox"==t(a.win).runtime||!!E(a.element)}
f.qa=function(){var a=this.element.scrollTop||1;this.A=this.element.scrollTop=a;null===this.ga&&Ba(this,a)};function Ba(a,b){a.ga=x(a.win,"timer").delay(function(){if(30>Math.abs(b-a.A)){a.ga=null;var c=a.A;Z(a,c,a.oa);a.oa=c;a.A=c}else Ba(a,a.A)},100)}function Z(a,b,c){var d=[];Ca(a,b,function(b){d.push(b);a.updateInViewport(b,!0);a.scheduleLayout(b)});c!=b&&Ca(a,c,function(b){d.includes(b)||a.updateInViewport(b,!1)})}
function Ca(a,b,c){a.ha||(a.ha={width:a.element.clientWidth,height:a.element.clientHeight});for(var d=a.ha.height,e=ta(a),g=0;g<e.length;g++){for(var h=e[g],k=0,q=h;q&&a.element.contains(q);q=q.offsetParent)k+=q.offsetTop;var r=2*d;k+h.offsetHeight>=b-r&&k<=b+r&&c(h)}}
function ya(a,b){var c;var d=a.win;c="amp-lightbox."+b;var e=w({}),g={detail:e};Object.assign(g,void 0);"function"==typeof d.CustomEvent?c=new d.CustomEvent(c,g):(d=d.document.createEvent("CustomEvent"),d.initCustomEvent(c,!!g.bubbles,!!g.cancelable,e),c=d);a.ia.trigger(a.element,b,c,100)}
function ra(a,b){var c={},d=x(a,"ampdoc").getAmpDoc();C(d,"resources").measureMutateElement(b,function g(){c.alreadyTransparent="rgba(0, 0, 0, 0)"==(a.getComputedStyle(b)||v())["background-color"]},function h(){if(!c.alreadyTransparent){if(!u.user)throw Error("failed to call initLogConstructor");u.user.warn("amp-lightbox","The background of the <body> element has been forced to transparent. If you need to set background, use an intermediate container.")}J(b,{background:"transparent"})})}
(function(a){"inabox"==t().runtime&&ra(window,document.body);a.registerElement("amp-lightbox",Y,"amp-lightbox{display:none;position:fixed!important;z-index:1000;top:0!important;left:0!important;bottom:0!important;right:0!important}amp-lightbox[scrollable]{overflow-y:auto!important;overflow-x:hidden!important}i-amphtml-ad-close-header{height:60px!important;display:block!important;visibility:visible!important;opacity:0;position:fixed!important;top:0!important;left:0!important;right:0!important;z-index:1000!important;display:-webkit-box!important;display:-ms-flexbox!important;display:flex!important;-webkit-box-align:center!important;-ms-flex-align:center!important;align-items:center!important;-webkit-box-pack:right!important;-ms-flex-pack:right!important;justify-content:right!important;-webkit-transition:opacity 0.1s ease-in;transition:opacity 0.1s ease-in}[animate-in=fly-in-bottom]>i-amphtml-ad-close-header,[animate-in=fly-in-top]>i-amphtml-ad-close-header{-webkit-transition-delay:0.2s;transition-delay:0.2s}.amp-ad-close-header{opacity:1!important;box-sizing:border-box;padding:5px;line-height:40px;background-color:#000;color:#fff;font-family:Helvetica,sans-serif;font-size:12px;cursor:pointer}.amp-ad-close-header>:first-child{margin-left:auto!important;pointer-events:none!important}.amp-ad-close-button{display:block!important;background:url(\"data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='24' fill='%23fff'%3E%3Cpath d='M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z'/%3E%3Cpath d='M0 0h24v24H0z' fill='none'/%3E%3C/svg%3E\") no-repeat;background-position:50%;width:40px;height:40px;pointer-events:none!important;border-radius:40px;margin-left:5px}.amp-ad-close-header:active>.amp-ad-close-button{background-color:hsla(0,0%,100%,0.3)}\n/*# sourceURL=/extensions/amp-lightbox/0.1/amp-lightbox.css*/")})(self.AMP);
})});
//# sourceMappingURL=amp-lightbox-0.1.js.map

