(self.AMP=self.AMP||[]).push({n:"amp-mustache",v:"1810052256480",f:(function(AMP,_){
function ba(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var e in b)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,e);d&&Object.defineProperty(a,e,d)}else a[e]=b[e]}function pa(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var qa=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function ra(a){var b=Object.create(null);if(!a)return b;for(var c;c=qa.exec(a);){var e=pa(c[1],c[1]),d=c[2]?pa(c[2],c[2]):"";b[e]=d}return b};self.log=self.log||{user:null,dev:null,userForEmbed:null};var sa=self.log;function z(){if(!sa.user)throw Error("failed to call initLogConstructor");return sa.user};function ta(a){return a||{}};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function ua(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};function va(a){if("content"in a)return a.content.cloneNode(!0);var b=a.ownerDocument.createDocumentFragment(),c=b,e=c.ownerDocument.createDocumentFragment();for(a=a.firstChild;a;a=a.nextSibling)e.appendChild(a.cloneNode(!0));c.appendChild(e);return b}function xa(a,b){for(var c=0,e;void 0!==(e=a[c]);c++)b(e,c)};function ya(a){this.L=a;this.G=this.H=0;this.F=Object.create(null)}ya.prototype.has=function(a){return!!this.F[a]};ya.prototype.get=function(a){var b=this.F[a];if(b)return b.access=++this.G,b.payload};
ya.prototype.put=function(a,b){this.has(a)||this.H++;this.F[a]={payload:b,access:this.G};if(!(this.H<=this.L)){if(sa.dev)a=sa.dev;else throw Error("failed to call initLogConstructor");a.warn("lru-cache","Trimming LRU cache");a=this.F;var c=this.G+1,e,d;for(d in a){var f=a[d].access;f<c&&(c=f,e=d)}void 0!==e&&(delete a[e],this.H--)}};var B=self.AMP_CONFIG||{},za={thirdParty:B.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:B.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof B.thirdPartyFrameRegex?new RegExp(B.thirdPartyFrameRegex):B.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:B.cdnUrl||"https://cdn.ampproject.org",cdnProxyRegex:("string"==typeof B.cdnProxyRegex?new RegExp(B.cdnProxyRegex):B.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,
errorReporting:B.errorReportingUrl||"https://amp-error-reporting.appspot.com/r",localDev:B.localDev||!1};var Aa=ta({c:!0,v:!0,a:!0,ad:!0}),Ba,Ca,Da=/[?&]amp_js[^&]*/,Fa=/[?&]amp_gsa[^&]*/,Ga=/[?&]amp_r[^&]*/,Ha=/[?&]usqp[^&]*/;
function L(a){var b;Ba||(Ba=self.document.createElement("a"),Ca=self.UrlCache||(self.UrlCache=new ya(100)));var c=b?null:Ca,e=Ba;if(c&&c.has(a))a=c.get(a);else{e.href=a;e.protocol||(e.href=e.href);var d={href:e.href,protocol:e.protocol,host:e.host,hostname:e.hostname,port:"0"==e.port?"":e.port,pathname:e.pathname,search:e.search,hash:e.hash,origin:null};"/"!==d.pathname[0]&&(d.pathname="/"+d.pathname);if("http:"==d.protocol&&80==d.port||"https:"==d.protocol&&443==d.port)d.port="",d.host=d.hostname;
d.origin=e.origin&&"null"!=e.origin?e.origin:"data:"!=d.protocol&&d.host?d.protocol+"//"+d.host:d.href;c&&c.put(a,d);a=d}return a}function Ia(a){"string"==typeof a&&(a=L(a));return za.cdnProxyRegex.test(a.origin)}
function Ja(a){"string"==typeof a&&(a=L(a));if(!Ia(a))return a.href;var b=a.pathname.split("/"),c=b[1];z().assert(Aa[c],"Unknown path prefix in url %s",a.href);var e=b[2],d="s"==e?"https://"+decodeURIComponent(b[3]):"http://"+decodeURIComponent(e);z().assert(0<d.indexOf("."),"Expected a . in origin %s",d);b.splice(1,"s"==e?3:2);b=d+b.join("/");c=(c=a.search)&&"?"!=c?(c=c.replace(Da,"").replace(Fa,"").replace(Ga,"").replace(Ha,"").replace(/^[?&]/,""))?"?"+c:"":"";return b+c+(a.hash||"")}
function Ka(a,b){"string"==typeof b&&(b=L(b));var c;if("function"==typeof URL)c=(new URL(a,b.href)).toString();else{c=a;var e=b;"string"==typeof e&&(e=L(e));c=c.replace(/\\/g,"/");var d=L(c);c=ua(c.toLowerCase(),d.protocol)?d.href:ua(c,"//")?e.protocol+c:ua(c,"/")?e.origin+c:e.origin+e.pathname.replace(/\/[^/]*$/,"/")+c}return c}function La(a){var b=L(a),c=ra(b.search);z().assert(!("__amp_source_origin"in c),"Source origin is not allowed in %s",a)};function Ma(a){a:{var b;try{b=a.document.cookie}catch(l){b=""}if(a=b)for(a=a.split(";"),b=0;b<a.length;b++){var c=a[b].trim(),e=c.indexOf("=");if(-1!=e&&"AMP_EXP"==pa(c.substring(0,e).trim(),void 0)){a=c.substring(e+1).trim();a=pa(a,a);break a}}a=null}var d=a,f=d?d.split(/\s*,\s*/g):[];a=Object.create(null);for(b=0;b<f.length;b++)0!=f[b].length&&("-"==f[b][0]?a[f[b].substr(1)]=!1:a[f[b]]=!0);return a};var Na=/(\S+)(?:\s+(?:(-?\d+(?:\.\d+)?)([a-zA-Z]*)))?\s*(?:,|$)/g;function Oa(a){for(var b=[],c;c=Na.exec(a);){var e=c[1],d=void 0,f;if(c[2]){var l=c[3].toLowerCase();if("w"==l)d=parseInt(c[2],10);else if("x"==l)f=parseFloat(c[2]);else continue}else f=1;b.push({url:e,width:d,dpr:f})}return new Pa(b)}
function Pa(a){z().assert(0<a.length,"Srcset must have at least one source");this.D=a;for(var b=!1,c=!1,e=0;e<a.length;e++)var d=a[e],b=b||!!d.width,c=c||!!d.dpr;z().assert(!!(b^c),"Srcset must have width or dpr sources, but not both");a.sort(b?Qa:Ra);this.K=b}
Pa.prototype.select=function(a,b){if(this.K){b*=a;a=this.D;for(var c=0,e=Infinity,d=Infinity,f=0;f<a.length;f++){var l=a[f].width,v=Math.abs(l-b);if(v<=1.1*e||1.2<b/d)c=f,e=v,d=l;else break}}else for(a=this.D,c=0,e=Infinity,d=0;d<a.length;d++)if(f=Math.abs(a[d].dpr-b),f<=e)c=d,e=f;else break;b=c;return this.D[b].url};Pa.prototype.getUrls=function(){return this.D.map(function(a){return a.url})};
Pa.prototype.stringify=function(a){for(var b=[],c=this.D,e=0;e<c.length;e++){var d=c[e],f=d.url;a&&(f=a(f));f=this.K?f+(" "+d.width+"w"):f+(" "+d.dpr+"x");b.push(f)}return b.join(", ")};function Qa(a,b){z().assert(a.width!=b.width,"Duplicate width: %s",a.width);return a.width-b.width}function Ra(a,b){z().assert(a.dpr!=b.dpr,"Duplicate dpr: %s",a.dpr);return a.dpr-b.dpr};var Sa="a abbr acronym address area article aside audio b bdi bdo big blink blockquote body br button canvas caption center cite code col colgroup content data datalist dd decorator del details dfn dir div dl dt element em fieldset figcaption figure font footer form h1 h2 h3 h4 h5 h6 head header hgroup hr html i img input ins kbd label legend li main map mark marquee menu menuitem meter nav nobr ol optgroup option output p pre progress q rp rt ruby s samp section select shadow small source spacer span strike strong style sub summary sup table tbody td template textarea tfoot th thead time tr track tt u ul var video wbr".split(" "),
Ta="svg a altglyph altglyphdef altglyphitem animatecolor animatemotion animatetransform audio canvas circle clippath defs desc ellipse filter font g glyph glyphref hkern image line lineargradient marker mask metadata mpath path pattern polygon polyline radialgradient rect stop style switch symbol text textpath title tref tspan video view vkern".split(" "),Ua="feBlend feColorMatrix feComponentTransfer feComposite feConvolveMatrix feDiffuseLighting feDisplacementMap feDistantLight feFlood feFuncA feFuncB feFuncG feFuncR feGaussianBlur feMerge feMergeNode feMorphology feOffset fePointLight feSpecularLighting feSpotLight feTile feTurbulence".split(" "),
Xa="math menclose merror mfenced mfrac mglyph mi mlabeledtr mmuliscripts mn mo mover mpadded mphantom mroot mrow ms mpspace msqrt mystyle msub msup msubsup mtable mtd mtext mtr munder munderover".split(" "),Ya=["#text"],Za="accept action align alt autocomplete background bgcolor border cellpadding cellspacing checked cite class clear color cols colspan coords crossorigin datetime default dir disabled download enctype face for headers height hidden high href hreflang id integrity ismap label lang list loop low max maxlength media method min multiple name noshade novalidate nowrap open optimum pattern placeholder poster preload pubdate radiogroup readonly rel required rev reversed role rows rowspan spellcheck scope selected shape size sizes span srclang start src srcset step style summary tabindex title type usemap valign value width xmlns".split(" "),
$a="accent-height accumulate additivive alignment-baseline ascent attributename attributetype azimuth basefrequency baseline-shift begin bias by class clip clip-path clip-rule color color-interpolation color-interpolation-filters color-profile color-rendering cx cy d dx dy diffuseconstant direction display divisor dur edgemode elevation end fill fill-opacity fill-rule filter flood-color flood-opacity font-family font-size font-size-adjust font-stretch font-style font-variant font-weight fx fy g1 g2 glyph-name glyphref gradientunits gradienttransform height href id image-rendering in in2 k k1 k2 k3 k4 kerning keypoints keysplines keytimes lang lengthadjust letter-spacing kernelmatrix kernelunitlength lighting-color local marker-end marker-mid marker-start markerheight markerunits markerwidth maskcontentunits maskunits max mask media method mode min name numoctaves offset operator opacity order orient orientation origin overflow paint-order path pathlength patterncontentunits patterntransform patternunits points preservealpha preserveaspectratio r rx ry radius refx refy repeatcount repeatdur restart result rotate scale seed shape-rendering specularconstant specularexponent spreadmethod stddeviation stitchtiles stop-color stop-opacity stroke-dasharray stroke-dashoffset stroke-linecap stroke-linejoin stroke-miterlimit stroke-opacity stroke stroke-width style surfacescale tabindex targetx targety transform text-anchor text-decoration text-rendering textlength type u1 u2 unicode values viewbox visibility vert-adv-y vert-origin-x vert-origin-y width word-spacing wrap writing-mode xchannelselector ychannelselector x x1 x2 xmlns y y1 y2 z zoomandpan".split(" "),
ab="accent accentunder align bevelled close columnsalign columnlines columnspan denomalign depth dir display displaystyle fence frame height href id largeop length linethickness lspace lquote mathbackground mathcolor mathsize mathvariant maxsize minsize movablelimits notation numalign open rowalign rowlines rowspacing rowspan rspace rquote scriptlevel scriptminsize scriptsizemultiplier selection separator separators stretchy subscriptshift supscriptshift symmetric voffset width xmlns".split(" "),
bb=["xlink:href","xml:id","xlink:title","xml:space","xmlns:xlink"];function P(a,b){for(var c=b.length;c--;)"string"===typeof b[c]&&(b[c]=b[c].toLowerCase()),a[b[c]]=!0;return a}function cb(a){var b={},c=void 0;for(c in a)Object.prototype.hasOwnProperty.call(a,c)&&(b[c]=a[c]);return b}
var db=/\{\{[\s\S]*|[\s\S]*\}\}/gm,eb=/<%[\s\S]*|[\s\S]*%>/gm,fb=/^data-[\-\w.\u00B7-\uFFFF]/,gb=/^aria-[\-\w]+$/,hb=/^(?:(?:(?:f|ht)tps?|mailto|tel|callto|cid|xmpp):|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i,ib=/^(?:\w+script|data):/i,jb=/[\u0000-\u0020\u00A0\u1680\u180E\u2000-\u2029\u205f\u3000]/g,kb="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"===typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a};
function Q(a){if(Array.isArray(a)){for(var b=0,c=Array(a.length);b<a.length;b++)c[b]=a[b];return c}return Array.from(a)}
function lb(){function a(a){var n,c,h,ca;e("beforeSanitizeAttributes",a,null);var m=a.attributes;if(m){var q={attrName:"",attrValue:"",keepAttr:!0,allowedAttributes:y};for(ca=m.length;ca--;){var d=n=m[ca],A=d.name,x=d.namespaceURI;n=n.value.trim();c=A.toLowerCase();q.attrName=c;q.attrValue=n;q.keepAttr=!0;e("uponSanitizeAttribute",a,q);n=q.attrValue;if("name"===c&&"IMG"===a.nodeName&&m.id)h=m.id,m=Array.prototype.slice.apply(m),g("id",a),g(A,a),m.indexOf(h)>ca&&a.setAttribute("id",h.value);else if("INPUT"!==
a.nodeName||"type"!==c||"file"!==n||!y[c]&&r[c])"id"===A&&a.setAttribute(A,""),g(A,a);else continue;if(q.keepAttr&&b(a.nodeName.toLowerCase(),c,n))try{x?a.setAttributeNS(x,A,n):a.setAttribute(A,n),u.removed.pop()}catch(Ob){}}e("afterSanitizeAttributes",a,null)}}function b(a,b,c){if(n&&("id"===b||"name"===b)&&(c in h||c in vb))return!1;I&&(c=c.replace(db," "),c=c.replace(eb," "));if(!H||!fb.test(b))if(!E||!gb.test(b))if(!y[b]||r[b]||!(Wa[b]||da.test(c.replace(jb,""))||("src"===b||"xlink:href"===b)&&
"script"!==a&&0===c.indexOf("data:")&&wb[a]||M&&!ib.test(c.replace(jb,"")))&&c)return!1;return!0}function c(a){var b;e("beforeSanitizeElements",a,null);if(f(a))return w(a),!0;b=a.nodeName.toLowerCase();e("uponSanitizeElement",a,{tagName:b,allowedTags:C});if(!C[b]||R[b]){if(m&&!q[b]&&"function"===typeof a.insertAdjacentHTML)try{a.insertAdjacentHTML("AfterEnd",a.innerHTML)}catch(ub){}w(a);return!0}!S||a.firstElementChild||a.content&&a.content.firstElementChild||!/</g.test(a.textContent)||(u.removed.push({element:a.cloneNode()}),
a.innerHTML=a.innerHTML?a.innerHTML.replace(/</g,"&lt;"):a.textContent.replace(/</g,"&lt;"));I&&3===a.nodeType&&(b=a.textContent,b=b.replace(db," "),b=b.replace(eb," "),a.textContent!==b&&(u.removed.push({element:a.cloneNode()}),a.textContent=b));e("afterSanitizeElements",a,null);return!1}function e(a,b,n){J[a]&&J[a].forEach(function(a){a.call(u,b,n,la)})}function d(a){return"object"===("undefined"===typeof G?"undefined":kb(G))?a instanceof G:a&&"object"===("undefined"===typeof a?"undefined":kb(a))&&
"number"===typeof a.nodeType&&"string"===typeof a.nodeName}function f(a){return a instanceof ea||a instanceof fa?!1:"string"===typeof a.nodeName&&"string"===typeof a.textContent&&"function"===typeof a.removeChild&&a.attributes instanceof ma&&"function"===typeof a.removeAttribute&&"function"===typeof a.setAttribute?!1:!0}function l(a){return ga.call(a.ownerDocument||a,a,K.SHOW_ELEMENT|K.SHOW_COMMENT|K.SHOW_TEXT,function(){return K.FILTER_ACCEPT},!1)}function v(a){var b=void 0;F&&(a="<remove></remove>"+
a);if(t)try{b=(new ha).parseFromString(a,"text/html")}catch(Ea){}T&&P(R,["title"]);if(!b||!b.documentElement){var n=b=na.createHTMLDocument(""),c=n.body;c.parentNode.removeChild(c.parentNode.firstElementChild);c.outerHTML=a}return ia.call(b,U?"html":"body")[0]}function g(a,b){try{u.removed.push({attribute:b.getAttributeNode(a),from:b})}catch(ub){u.removed.push({attribute:null,from:b})}b.removeAttribute(a)}function w(a){u.removed.push({element:a});try{a.parentNode.removeChild(a)}catch(Va){a.outerHTML=
""}}function V(a){"object"!==("undefined"===typeof a?"undefined":kb(a))&&(a={});C="ALLOWED_TAGS"in a?P({},a.ALLOWED_TAGS):Z;y="ALLOWED_ATTR"in a?P({},a.ALLOWED_ATTR):N;R="FORBID_TAGS"in a?P({},a.FORBID_TAGS):{};r="FORBID_ATTR"in a?P({},a.FORBID_ATTR):{};A="USE_PROFILES"in a?a.USE_PROFILES:!1;E=!1!==a.ALLOW_ARIA_ATTR;H=!1!==a.ALLOW_DATA_ATTR;M=a.ALLOW_UNKNOWN_PROTOCOLS||!1;S=a.SAFE_FOR_JQUERY||!1;I=a.SAFE_FOR_TEMPLATES||!1;U=a.WHOLE_DOCUMENT||!1;W=a.RETURN_DOM||!1;oa=a.RETURN_DOM_FRAGMENT||!1;D=a.RETURN_DOM_IMPORT||
!1;F=a.FORCE_BODY||!1;n=!1!==a.SANITIZE_DOM;m=!1!==a.KEEP_CONTENT;x=a.IN_PLACE||!1;da=a.ALLOWED_URI_REGEXP||da;I&&(H=!1);oa&&(W=!0);A&&(C=P({},[].concat(Q(Ya))),y=[],!0===A.html&&(P(C,Sa),P(y,Za)),!0===A.svg&&(P(C,Ta),P(y,$a),P(y,bb)),!0===A.svgFilters&&(P(C,Ua),P(y,$a),P(y,bb)),!0===A.mathMl&&(P(C,Xa),P(y,ab),P(y,bb)));a.ADD_TAGS&&(C===Z&&(C=cb(C)),P(C,a.ADD_TAGS));a.ADD_ATTR&&(y===N&&(y=cb(y)),P(y,a.ADD_ATTR));a.ADD_URI_SAFE_ATTR&&P(Wa,a.ADD_URI_SAFE_ATTR);m&&(C["#text"]=!0);U&&P(C,["html","head",
"body"]);C.table&&P(C,["tbody"]);Object&&"freeze"in Object&&Object.freeze(a);la=a}function u(a){return lb(a)}var k=0<arguments.length&&void 0!==arguments[0]?arguments[0]:"undefined"===typeof window?null:window;u.version="1.0.8";u.removed=[];if(!k||!k.document||9!==k.document.nodeType)return u.isSupported=!1,u;var p=k.document,t=!1,T=!1,h=k.document,aa=k.DocumentFragment,G=k.Node,K=k.NodeFilter,X=k.NamedNodeMap,ma=void 0===X?k.NamedNodeMap||k.MozNamedAttrMap:X,ea=k.Text,fa=k.Comment,ha=k.DOMParser;
"function"===typeof k.HTMLTemplateElement&&(X=h.createElement("template"),X.content&&X.content.ownerDocument&&(h=X.content.ownerDocument));var O=h,na=O.implementation,ga=O.createNodeIterator,ia=O.getElementsByTagName,wa=O.createDocumentFragment,ja=p.importNode,J={};u.isSupported=na&&"undefined"!==typeof na.createHTMLDocument&&9!==h.documentMode;var da=hb,C=null,Z=P({},[].concat(Q(Sa),Q(Ta),Q(Ua),Q(Xa),Q(Ya))),y=null,N=P({},[].concat(Q(Za),Q($a),Q(ab),Q(bb))),R=null,r=null,E=!0,H=!0,M=!1,S=!1,I=!1,
U=!1,ka=!1,F=!1,W=!1,oa=!1,D=!1,n=!0,m=!0,x=!1,A={},q=P({},"audio head math script style template svg video".split(" ")),wb=P({},["audio","video","img","source","image"]),Wa=P({},"alt class for id label name pattern placeholder summary title value style xmlns".split(" ")),la=null,vb=h.createElement("form");u.isSupported&&(function(){try{v('<svg><p><style><img src="</style><img src=x onerror=alert(1)//">').querySelector("svg img")&&(t=!0)}catch(ca){}}(),function(){try{v("<x/><title>&lt;/title&gt;&lt;img&gt;").querySelector("title").textContent.match(/<\/title/)&&
(T=!0)}catch(ca){}}());var xb=function Va(b){var n=void 0,h=l(b);for(e("beforeSanitizeShadowDOM",b,null);n=h.nextNode();)e("uponSanitizeShadowNode",n,null),c(n)||(n.content instanceof aa&&Va(n.content),a(n));e("afterSanitizeShadowDOM",b,null)};u.sanitize=function(b,n){var h=void 0,m=void 0,q=void 0,e=void 0;b||(b="\x3c!--\x3e");if("string"!==typeof b&&!d(b)){if("function"!==typeof b.toString)throw new TypeError("toString is not a function");b=b.toString();if("string"!==typeof b)throw new TypeError("dirty is not a string, aborting");
}if(!u.isSupported){if("object"===kb(k.toStaticHTML)||"function"===typeof k.toStaticHTML){if("string"===typeof b)return k.toStaticHTML(b);if(d(b))return k.toStaticHTML(b.outerHTML)}return b}ka||V(n);u.removed=[];if(!x)if(b instanceof G)h=v("\x3c!--\x3e"),m=h.ownerDocument.importNode(b,!0),1===m.nodeType&&"BODY"===m.nodeName?h=m:h.appendChild(m);else{if(!W&&!U&&-1===b.indexOf("<"))return b;h=v(b);if(!h)return W?null:""}h&&F&&w(h.firstChild);for(var g=l(x?b:h);n=g.nextNode();)3===n.nodeType&&n===q||
c(n)||(n.content instanceof aa&&xb(n.content),a(n),q=n);if(x)return b;if(W){if(oa)for(e=wa.call(h.ownerDocument);h.firstChild;)e.appendChild(h.firstChild);else e=h;D&&(e=ja.call(p,e,!0));return e}return U?h.outerHTML:h.innerHTML};u.setConfig=function(a){V(a);ka=!0};u.clearConfig=function(){la=null;ka=!1};u.isValidAttribute=function(a,n,c){la||V({});return b(a.toLowerCase(),n.toLowerCase(),c)};u.addHook=function(a,b){"function"===typeof b&&(J[a]=J[a]||[],J[a].push(b))};u.removeHook=function(a){J[a]&&
J[a].pop()};u.removeHooks=function(a){J[a]&&(J[a]=[])};u.removeAllHooks=function(){J={}};return u}lb();var mb={applet:!0,audio:!0,base:!0,embed:!0,frame:!0,frameset:!0,iframe:!0,img:!0,link:!0,meta:!0,object:!0,style:!0,video:!0},nb="a b br caption colgroup code del div em i ins li mark ol p q s small span strong sub sup table tbody time td th thead tfoot tr u ul".split(" "),ob="amp-fx fallback heights layout min-font-size max-font-size on option placeholder submitting submit-success submit-error validation-for verify-error visible-when-invalid href style text subscriptions-action subscriptions-actions subscriptions-decorate subscriptions-dialog subscriptions-display subscriptions-section subscriptions-service".split(" "),
pb={a:["rel","target"],div:["template"],form:["action-xhr","verify-xhr","custom-validation-reporting","target"],template:["type"]},qb=["_top","_blank"],rb=["javascript:","vbscript:","data:","<script","\x3c/script"],sb=ta({input:{type:/(?:image|button)/i}}),tb="form formaction formmethod formtarget formnovalidate formenctype".split(" "),yb=ta({input:tb,textarea:tb,select:tb}),zb=/!important|position\s*:\s*fixed|position\s*:\s*sticky/i;
function Ab(a,b,c){var e;e=void 0===e?!1:e;if(!e){if(ua(b,"on")&&"on"!=b)return!1;if(c)for(var d=c.toLowerCase().replace(/[\s,\u0000]+/g,""),f=0;f<rb.length;f++)if(0<=d.indexOf(rb[f]))return!1}if("style"==b)return!zb.test(c);if("class"==b&&c&&/(^|\W)i-amphtml-/i.test(c))return!1;var l=yb[a];if(l&&-1!=l.indexOf(b))return!1;var v=sb[a];if(v){var g=v[b];if(g&&-1!=c.search(g))return!1}return!0}function Bb(a,b,c){a=a.toLowerCase();b=b.toLowerCase();return"src"==b||"href"==b||"srcset"==b?Cb(a,b,c):c}
function Cb(a,b,c){var e=self.location;La(c);var d=Ia(e),f=L(Ja(e));if("href"==b&&!ua(c,"#"))return Ka(c,f);if("src"==b)return"amp-img"==a?Db(c,f,d):Ka(c,f);if("srcset"==b){var l;try{l=Oa(c)}catch(v){return z().error("purifier","Failed to parse srcset: ",v),c}return l.stringify(function(a){return Db(a,f,d)})}return c}
function Db(a,b,c){a=L(Ka(a,b));return"data:"==a.protocol||Ia(a)||!c?a.href:za.cdn+"/i/"+("https:"==a.protocol?"s/":"")+encodeURIComponent(a.host)+a.pathname+(a.search||"")+(a.hash||"")};var Eb=function(){function a(a){var b=(""+a).match(p);return b?new g(w(b[1]),w(b[2]),w(b[3]),w(b[4]),w(b[5]),w(b[6]),w(b[7])):null}function b(a,b,f,k,l,w,p){a=new g(e(a,t),e(b,t),c(f),0<k?k.toString():null,e(l,T),null,c(p));w&&("string"===typeof w?a.setRawQuery(w.replace(/[^?&=0-9A-Za-z_\-~.%]/g,d)):a.setAllParameters(w));return a}function c(a){return"string"==typeof a?encodeURIComponent(a):null}function e(a,b){return"string"==typeof a?encodeURI(a).replace(b,d):null}function d(a){var b=a.charCodeAt(0);
return"%"+"0123456789ABCDEF".charAt(b>>4&15)+"0123456789ABCDEF".charAt(b&15)}function f(a){return a.replace(/(^|\/)\.(?:\/|$)/g,"$1").replace(/\/{2,}/g,"/")}function l(a){if(null===a)return null;a=f(a);for(var b=u,c;(c=a.replace(b,"$1"))!=a;a=c);return a}function v(a,b){var c=a.clone(),h=b.hasScheme();h?c.setRawScheme(b.getRawScheme()):h=b.hasCredentials();h?c.setRawCredentials(b.getRawCredentials()):h=b.hasDomain();h?c.setRawDomain(b.getRawDomain()):h=b.hasPort();var e=b.getRawPath(),d=l(e);if(h)c.setPort(b.getPort()),
d=d&&d.replace(k,"");else if(h=!!e){if(47!==d.charCodeAt(0))var g=l(c.getRawPath()||"").replace(k,""),f=g.lastIndexOf("/")+1,d=l((f?g.substring(0,f):"")+l(e)).replace(k,"")}else d=d&&d.replace(k,""),d!==e&&c.setRawPath(d);h?c.setRawPath(d):h=b.hasQuery();h?c.setRawQuery(b.getRawQuery()):h=b.hasFragment();h&&c.setRawFragment(b.getRawFragment());return c}function g(a,b,c,e,d,g,f){this.A=a;this.m=b;this.o=c;this.B=e;this.l=d;this.j=g;this.w=f;this.h=null}function w(a){return"string"==typeof a&&0<a.length?
a:null}var V=/(\/|^)(?:[^./][^/]*|\.{2,}(?:[^./][^/]*)|\.{3,}[^/]*)\/\.\.(?:\/|$)/,u=new RegExp(V),k=/^(?:\.\.\/)*(?:\.\.$)?/;g.prototype.toString=function(){var a=[];null!==this.A&&a.push(this.A,":");null!==this.o&&(a.push("//"),null!==this.m&&a.push(this.m,"@"),a.push(this.o),null!==this.B&&a.push(":",this.B.toString()));null!==this.l&&a.push(this.l);null!==this.j&&a.push("?",this.j);null!==this.w&&a.push("#",this.w);return a.join("")};g.prototype.clone=function(){return new g(this.A,this.m,this.o,
this.B,this.l,this.j,this.w)};g.prototype.getScheme=function(){return this.A&&decodeURIComponent(this.A).toLowerCase()};g.prototype.getRawScheme=function(){return this.A};g.prototype.setScheme=function(a){this.A=e(a,t);return this};g.prototype.setRawScheme=function(a){this.A=a?a:null;return this};g.prototype.hasScheme=function(){return null!==this.A};g.prototype.getCredentials=function(){return this.m&&decodeURIComponent(this.m)};g.prototype.getRawCredentials=function(){return this.m};g.prototype.setCredentials=
function(a){this.m=e(a,t);return this};g.prototype.setRawCredentials=function(a){this.m=a?a:null;return this};g.prototype.hasCredentials=function(){return null!==this.m};g.prototype.getDomain=function(){return this.o&&decodeURIComponent(this.o)};g.prototype.getRawDomain=function(){return this.o};g.prototype.setDomain=function(a){return this.setRawDomain(a&&encodeURIComponent(a))};g.prototype.setRawDomain=function(a){this.o=a?a:null;return this.setRawPath(this.l)};g.prototype.hasDomain=function(){return null!==
this.o};g.prototype.getPort=function(){return this.B&&decodeURIComponent(this.B)};g.prototype.setPort=function(a){if(a){a=Number(a);if(a!==(a&65535))throw Error("Bad port number "+a);this.B=""+a}else this.B=null;return this};g.prototype.hasPort=function(){return null!==this.B};g.prototype.getPath=function(){return this.l&&decodeURIComponent(this.l)};g.prototype.getRawPath=function(){return this.l};g.prototype.setPath=function(a){return this.setRawPath(e(a,T))};g.prototype.setRawPath=function(a){a?
(a=String(a),this.l=!this.o||/^\//.test(a)?a:"/"+a):this.l=null;return this};g.prototype.hasPath=function(){return null!==this.l};g.prototype.getQuery=function(){return this.j&&decodeURIComponent(this.j).replace(/\+/g," ")};g.prototype.getRawQuery=function(){return this.j};g.prototype.setQuery=function(a){this.h=null;this.j=c(a);return this};g.prototype.setRawQuery=function(a){this.h=null;this.j=a?a:null;return this};g.prototype.hasQuery=function(){return null!==this.j};g.prototype.setAllParameters=
function(a){if("object"===typeof a&&!(a instanceof Array)&&(a instanceof Object||"[object Array]"!==Object.prototype.toString.call(a))){var b=[],c=-1,e;for(e in a){var d=a[e];"string"===typeof d&&(b[++c]=e,b[++c]=d)}a=b}this.h=null;for(var g=[],h="",f=0;f<a.length;)e=a[f++],d=a[f++],g.push(h,encodeURIComponent(e.toString())),h="&",d&&g.push("=",encodeURIComponent(d.toString()));this.j=g.join("");return this};g.prototype.C=function(){if(!this.h){var a=this.j;if(a){for(var b=a.split(/[&\?]/),a=[],c=
-1,e=0;e<b.length;++e){var d=b[e].match(/^([^=]*)(?:=(.*))?$/);a[++c]=decodeURIComponent(d[1]).replace(/\+/g," ");a[++c]=decodeURIComponent(d[2]||"").replace(/\+/g," ")}this.h=a}else this.h=[]}};g.prototype.setParameterValues=function(a,b){"string"===typeof b&&(b=[b]);this.C();for(var c=0,e=this.h,d=[],g=0;g<e.length;g+=2)a===e[g]?c<b.length&&d.push(a,b[c++]):d.push(e[g],e[g+1]);for(;c<b.length;)d.push(a,b[c++]);this.setAllParameters(d);return this};g.prototype.removeParameter=function(a){return this.setParameterValues(a,
[])};g.prototype.getAllParameters=function(){this.C();return this.h.slice(0,this.h.length)};g.prototype.getParameterValues=function(a){this.C();for(var b=[],c=0;c<this.h.length;c+=2)a===this.h[c]&&b.push(this.h[c+1]);return b};g.prototype.getParameterMap=function(){this.C();for(var a={},b=0;b<this.h.length;b+=2){var c=this.h[b++],e=this.h[b++];c in a?a[c].push(e):a[c]=[e]}return a};g.prototype.getParameterValue=function(a){this.C();for(var b=0;b<this.h.length;b+=2)if(a===this.h[b])return this.h[b+
1];return null};g.prototype.getFragment=function(){return this.w&&decodeURIComponent(this.w)};g.prototype.getRawFragment=function(){return this.w};g.prototype.setFragment=function(a){this.w=a?encodeURIComponent(a):null;return this};g.prototype.setRawFragment=function(a){this.w=a?a:null;return this};g.prototype.hasFragment=function(){return null!==this.w};var p=/^(?:([^:/?#]+):)?(?:\/\/(?:([^/?#]*)@)?([^/?#:@]*)(?::([0-9]+))?)?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,t=/[#\/\?@]/g,T=/[\#\?]/g;g.parse=a;
g.create=b;g.resolve=v;g.collapse_dots=l;g.utils={mimeTypeOf:function(b){var c=a(b);return/\.html$/.test(c.getPath())?"text/html":"application/javascript"},resolve:function(b,c){return b?v(a(b),a(c)).toString():""+c}};return g}(),Y={atype:{NONE:0,URI:1,URI_FRAGMENT:11,SCRIPT:2,STYLE:3,HTML:12,ID:4,IDREF:5,IDREFS:6,GLOBAL_NAME:7,LOCAL_NAME:8,CLASSES:9,FRAME_TARGET:10,MEDIA_QUERY:13}};Y.atype=Y.atype;
Y.ATTRIBS={"*::class":9,"*::dir":0,"*::draggable":0,"*::hidden":0,"*::id":4,"*::inert":0,"*::itemprop":0,"*::itemref":6,"*::itemscope":0,"*::lang":0,"*::onblur":2,"*::onchange":2,"*::onclick":2,"*::ondblclick":2,"*::onerror":2,"*::onfocus":2,"*::onkeydown":2,"*::onkeypress":2,"*::onkeyup":2,"*::onload":2,"*::onmousedown":2,"*::onmousemove":2,"*::onmouseout":2,"*::onmouseover":2,"*::onmouseup":2,"*::onreset":2,"*::onscroll":2,"*::onselect":2,"*::onsubmit":2,"*::ontouchcancel":2,"*::ontouchend":2,"*::ontouchenter":2,
"*::ontouchleave":2,"*::ontouchmove":2,"*::ontouchstart":2,"*::onunload":2,"*::spellcheck":0,"*::style":3,"*::tabindex":0,"*::title":0,"*::translate":0,"a::accesskey":0,"a::coords":0,"a::href":1,"a::hreflang":0,"a::name":7,"a::onblur":2,"a::onfocus":2,"a::shape":0,"a::target":10,"a::type":0,"area::accesskey":0,"area::alt":0,"area::coords":0,"area::href":1,"area::nohref":0,"area::onblur":2,"area::onfocus":2,"area::shape":0,"area::target":10,"audio::controls":0,"audio::loop":0,"audio::mediagroup":5,
"audio::muted":0,"audio::preload":0,"audio::src":1,"bdo::dir":0,"blockquote::cite":1,"br::clear":0,"button::accesskey":0,"button::disabled":0,"button::name":8,"button::onblur":2,"button::onfocus":2,"button::type":0,"button::value":0,"canvas::height":0,"canvas::width":0,"caption::align":0,"col::align":0,"col::char":0,"col::charoff":0,"col::span":0,"col::valign":0,"col::width":0,"colgroup::align":0,"colgroup::char":0,"colgroup::charoff":0,"colgroup::span":0,"colgroup::valign":0,"colgroup::width":0,
"command::checked":0,"command::command":5,"command::disabled":0,"command::icon":1,"command::label":0,"command::radiogroup":0,"command::type":0,"data::value":0,"del::cite":1,"del::datetime":0,"details::open":0,"dir::compact":0,"div::align":0,"dl::compact":0,"fieldset::disabled":0,"font::color":0,"font::face":0,"font::size":0,"form::accept":0,"form::action":1,"form::autocomplete":0,"form::enctype":0,"form::method":0,"form::name":7,"form::novalidate":0,"form::onreset":2,"form::onsubmit":2,"form::target":10,
"h1::align":0,"h2::align":0,"h3::align":0,"h4::align":0,"h5::align":0,"h6::align":0,"hr::align":0,"hr::noshade":0,"hr::size":0,"hr::width":0,"iframe::align":0,"iframe::frameborder":0,"iframe::height":0,"iframe::marginheight":0,"iframe::marginwidth":0,"iframe::width":0,"img::align":0,"img::alt":0,"img::border":0,"img::height":0,"img::hspace":0,"img::ismap":0,"img::name":7,"img::src":1,"img::usemap":11,"img::vspace":0,"img::width":0,"input::accept":0,"input::accesskey":0,"input::align":0,"input::alt":0,
"input::autocomplete":0,"input::checked":0,"input::disabled":0,"input::inputmode":0,"input::ismap":0,"input::list":5,"input::max":0,"input::maxlength":0,"input::min":0,"input::multiple":0,"input::name":8,"input::onblur":2,"input::onchange":2,"input::onfocus":2,"input::onselect":2,"input::pattern":0,"input::placeholder":0,"input::readonly":0,"input::required":0,"input::size":0,"input::src":1,"input::step":0,"input::type":0,"input::usemap":11,"input::value":0,"ins::cite":1,"ins::datetime":0,"label::accesskey":0,
"label::for":5,"label::onblur":2,"label::onfocus":2,"legend::accesskey":0,"legend::align":0,"li::type":0,"li::value":0,"map::name":7,"menu::compact":0,"menu::label":0,"menu::type":0,"meter::high":0,"meter::low":0,"meter::max":0,"meter::min":0,"meter::optimum":0,"meter::value":0,"ol::compact":0,"ol::reversed":0,"ol::start":0,"ol::type":0,"optgroup::disabled":0,"optgroup::label":0,"option::disabled":0,"option::label":0,"option::selected":0,"option::value":0,"output::for":6,"output::name":8,"p::align":0,
"pre::width":0,"progress::max":0,"progress::min":0,"progress::value":0,"q::cite":1,"select::autocomplete":0,"select::disabled":0,"select::multiple":0,"select::name":8,"select::onblur":2,"select::onchange":2,"select::onfocus":2,"select::required":0,"select::size":0,"source::src":1,"source::type":0,"table::align":0,"table::bgcolor":0,"table::border":0,"table::cellpadding":0,"table::cellspacing":0,"table::frame":0,"table::rules":0,"table::summary":0,"table::width":0,"tbody::align":0,"tbody::char":0,
"tbody::charoff":0,"tbody::valign":0,"td::abbr":0,"td::align":0,"td::axis":0,"td::bgcolor":0,"td::char":0,"td::charoff":0,"td::colspan":0,"td::headers":6,"td::height":0,"td::nowrap":0,"td::rowspan":0,"td::scope":0,"td::valign":0,"td::width":0,"template::type":0,"textarea::accesskey":0,"textarea::autocomplete":0,"textarea::cols":0,"textarea::disabled":0,"textarea::inputmode":0,"textarea::name":8,"textarea::onblur":2,"textarea::onchange":2,"textarea::onfocus":2,"textarea::onselect":2,"textarea::placeholder":0,
"textarea::readonly":0,"textarea::required":0,"textarea::rows":0,"textarea::wrap":0,"tfoot::align":0,"tfoot::char":0,"tfoot::charoff":0,"tfoot::valign":0,"th::abbr":0,"th::align":0,"th::axis":0,"th::bgcolor":0,"th::char":0,"th::charoff":0,"th::colspan":0,"th::headers":6,"th::height":0,"th::nowrap":0,"th::rowspan":0,"th::scope":0,"th::valign":0,"th::width":0,"thead::align":0,"thead::char":0,"thead::charoff":0,"thead::valign":0,"tr::align":0,"tr::bgcolor":0,"tr::char":0,"tr::charoff":0,"tr::valign":0,
"track::default":0,"track::kind":0,"track::label":0,"track::srclang":0,"ul::compact":0,"ul::type":0,"video::controls":0,"video::height":0,"video::loop":0,"video::mediagroup":5,"video::muted":0,"video::poster":1,"video::preload":0,"video::src":1,"video::width":0};Y.ATTRIBS=Y.ATTRIBS;Y.eflags={OPTIONAL_ENDTAG:1,EMPTY:2,CDATA:4,RCDATA:8,UNSAFE:16,FOLDABLE:32,SCRIPT:64,STYLE:128,VIRTUALIZED:256};Y.eflags=Y.eflags;
Y.ELEMENTS={a:0,abbr:0,acronym:0,address:0,applet:272,area:2,article:0,aside:0,audio:0,b:0,base:274,basefont:274,bdi:0,bdo:0,big:0,blockquote:0,body:305,br:2,button:0,canvas:0,caption:0,center:0,cite:0,code:0,col:2,colgroup:1,command:2,data:0,datalist:0,dd:1,del:0,details:0,dfn:0,dialog:272,dir:0,div:0,dl:0,dt:1,em:0,fieldset:0,figcaption:0,figure:0,font:0,footer:0,form:0,frame:274,frameset:272,h1:0,h2:0,h3:0,h4:0,h5:0,h6:0,head:305,header:0,hgroup:0,hr:2,html:305,i:0,iframe:4,img:2,input:2,ins:0,
isindex:274,kbd:0,keygen:274,label:0,legend:0,li:1,link:274,map:0,mark:0,menu:0,meta:274,meter:0,nav:0,nobr:0,noembed:276,noframes:276,noscript:276,object:272,ol:0,optgroup:0,option:1,output:0,p:1,param:274,pre:0,progress:0,q:0,s:0,samp:0,script:84,section:0,select:0,small:0,source:2,span:0,strike:0,strong:0,style:148,sub:0,summary:0,sup:0,table:0,tbody:1,td:1,template:4,textarea:8,tfoot:1,th:1,thead:1,time:0,title:280,tr:1,track:2,tt:0,u:0,ul:0,"var":0,video:0,wbr:2};Y.ELEMENTS=Y.ELEMENTS;
Y.ELEMENT_DOM_INTERFACES={a:"HTMLAnchorElement",abbr:"HTMLElement",acronym:"HTMLElement",address:"HTMLElement",applet:"HTMLAppletElement",area:"HTMLAreaElement",article:"HTMLElement",aside:"HTMLElement",audio:"HTMLAudioElement",b:"HTMLElement",base:"HTMLBaseElement",basefont:"HTMLBaseFontElement",bdi:"HTMLElement",bdo:"HTMLElement",big:"HTMLElement",blockquote:"HTMLQuoteElement",body:"HTMLBodyElement",br:"HTMLBRElement",button:"HTMLButtonElement",canvas:"HTMLCanvasElement",caption:"HTMLTableCaptionElement",
center:"HTMLElement",cite:"HTMLElement",code:"HTMLElement",col:"HTMLTableColElement",colgroup:"HTMLTableColElement",command:"HTMLCommandElement",data:"HTMLElement",datalist:"HTMLDataListElement",dd:"HTMLElement",del:"HTMLModElement",details:"HTMLDetailsElement",dfn:"HTMLElement",dialog:"HTMLDialogElement",dir:"HTMLDirectoryElement",div:"HTMLDivElement",dl:"HTMLDListElement",dt:"HTMLElement",em:"HTMLElement",fieldset:"HTMLFieldSetElement",figcaption:"HTMLElement",figure:"HTMLElement",font:"HTMLFontElement",
footer:"HTMLElement",form:"HTMLFormElement",frame:"HTMLFrameElement",frameset:"HTMLFrameSetElement",h1:"HTMLHeadingElement",h2:"HTMLHeadingElement",h3:"HTMLHeadingElement",h4:"HTMLHeadingElement",h5:"HTMLHeadingElement",h6:"HTMLHeadingElement",head:"HTMLHeadElement",header:"HTMLElement",hgroup:"HTMLElement",hr:"HTMLHRElement",html:"HTMLHtmlElement",i:"HTMLElement",iframe:"HTMLIFrameElement",img:"HTMLImageElement",input:"HTMLInputElement",ins:"HTMLModElement",isindex:"HTMLUnknownElement",kbd:"HTMLElement",
keygen:"HTMLKeygenElement",label:"HTMLLabelElement",legend:"HTMLLegendElement",li:"HTMLLIElement",link:"HTMLLinkElement",map:"HTMLMapElement",mark:"HTMLElement",menu:"HTMLMenuElement",meta:"HTMLMetaElement",meter:"HTMLMeterElement",nav:"HTMLElement",nobr:"HTMLElement",noembed:"HTMLElement",noframes:"HTMLElement",noscript:"HTMLElement",object:"HTMLObjectElement",ol:"HTMLOListElement",optgroup:"HTMLOptGroupElement",option:"HTMLOptionElement",output:"HTMLOutputElement",p:"HTMLParagraphElement",param:"HTMLParamElement",
pre:"HTMLPreElement",progress:"HTMLProgressElement",q:"HTMLQuoteElement",s:"HTMLElement",samp:"HTMLElement",script:"HTMLScriptElement",section:"HTMLElement",select:"HTMLSelectElement",small:"HTMLElement",source:"HTMLSourceElement",span:"HTMLSpanElement",strike:"HTMLElement",strong:"HTMLElement",style:"HTMLStyleElement",sub:"HTMLElement",summary:"HTMLElement",sup:"HTMLElement",table:"HTMLTableElement",tbody:"HTMLTableSectionElement",td:"HTMLTableDataCellElement",template:"HTMLTemplateElement",textarea:"HTMLTextAreaElement",
tfoot:"HTMLTableSectionElement",th:"HTMLTableHeaderCellElement",thead:"HTMLTableSectionElement",time:"HTMLTimeElement",title:"HTMLTitleElement",tr:"HTMLTableRowElement",track:"HTMLTrackElement",tt:"HTMLElement",u:"HTMLElement",ul:"HTMLUListElement","var":"HTMLElement",video:"HTMLVideoElement",wbr:"HTMLElement"};Y.ELEMENT_DOM_INTERFACES=Y.ELEMENT_DOM_INTERFACES;Y.ueffects={NOT_LOADED:0,SAME_DOCUMENT:1,NEW_DOCUMENT:2};Y.ueffects=Y.ueffects;
Y.URIEFFECTS={"a::href":2,"area::href":2,"audio::src":1,"blockquote::cite":0,"command::icon":1,"del::cite":0,"form::action":2,"img::src":1,"input::src":1,"ins::cite":0,"q::cite":0,"video::poster":1,"video::src":1};Y.URIEFFECTS=Y.URIEFFECTS;Y.ltypes={UNSANDBOXED:2,SANDBOXED:1,DATA:0};Y.ltypes=Y.ltypes;
Y.LOADERTYPES={"a::href":2,"area::href":2,"audio::src":2,"blockquote::cite":2,"command::icon":1,"del::cite":2,"form::action":2,"img::src":1,"input::src":1,"ins::cite":2,"q::cite":2,"video::poster":1,"video::src":2};Y.LOADERTYPES=Y.LOADERTYPES;
var Fb=function(a){function b(a){if(ja.hasOwnProperty(a))return ja[a];var b=a.match(J);return b?String.fromCharCode(parseInt(b[1],10)):(b=a.match(da))?String.fromCharCode(parseInt(b[1],16)):Z&&C.test(a)?(Z.innerHTML="&"+a+";",b=Z.textContent,ja[a]=b):"&"+a+";"}function c(a,c){return b(c)}function e(a){return a.replace(y,"")}function d(a){return a.replace(N,c)}function f(a){return(""+a).replace(r,"&amp;").replace(H,"&lt;").replace(M,"&gt;").replace(S,"&#34;")}function l(a){return a.replace(E,"&amp;$1").replace(H,
"&lt;").replace(M,"&gt;")}function v(a){var b={cdata:a.cdata||a.cdata,comment:a.comment||a.comment,endDoc:a.endDoc||a.endDoc,endTag:a.endTag||a.endTag,pcdata:a.pcdata||a.pcdata,rcdata:a.rcdata||a.rcdata,startDoc:a.startDoc||a.startDoc,startTag:a.startTag||a.startTag};return function(a,c){var n=b,e=V(a);w(n,e,0,{noMoreGT:!1,noMoreEndComments:!1},c)}}function g(a,b,c,e,d){return function(){w(a,b,c,e,d)}}function w(b,c,e,d,q){try{b.startDoc&&0==e&&b.startDoc(q);for(var n,m,x,f=e,A=c.length;f<A;){var h=
c[f++],l=c[f];switch(h){case "&":R.test(l)?(b.pcdata&&b.pcdata("&"+l,q,F,g(b,c,f,d,q)),f++):b.pcdata&&b.pcdata("&amp;",q,F,g(b,c,f,d,q));break;case "</":(n=/^([-\w:]+)[^\'\"]*/.exec(l))?n[0].length===l.length&&">"===c[f+1]?(f+=2,x=n[1].toLowerCase(),b.endTag&&b.endTag(x,q,F,g(b,c,f,d,q))):f=u(c,f,b,q,F,d):b.pcdata&&b.pcdata("&lt;/",q,F,g(b,c,f,d,q));break;case "<":if(n=/^([-\w:]+)\s*\/?/.exec(l))if(n[0].length===l.length&&">"===c[f+1]){f+=2;x=n[1].toLowerCase();b.startTag&&b.startTag(x,[],q,F,g(b,
c,f,d,q));var r=a.ELEMENTS[x];r&ka&&(f=p(c,{name:x,next:f,eflags:r},b,q,F,d))}else f=k(c,f,b,q,F,d);else b.pcdata&&b.pcdata("&lt;",q,F,g(b,c,f,d,q));break;case "\x3c!--":if(!d.noMoreEndComments){for(m=f+1;m<A&&(">"!==c[m]||!/--$/.test(c[m-1]));m++);if(m<A){if(b.comment){var y=c.slice(f,m).join("");b.comment(y.substr(0,y.length-2),q,F,g(b,c,m+1,d,q))}f=m+1}else d.noMoreEndComments=!0}d.noMoreEndComments&&b.pcdata&&b.pcdata("&lt;!--",q,F,g(b,c,f,d,q));break;case "<!":if(/^\w/.test(l)){if(!d.noMoreGT){for(m=
f+1;m<A&&">"!==c[m];m++);m<A?f=m+1:d.noMoreGT=!0}d.noMoreGT&&b.pcdata&&b.pcdata("&lt;!",q,F,g(b,c,f,d,q))}else b.pcdata&&b.pcdata("&lt;!",q,F,g(b,c,f,d,q));break;case "<?":if(!d.noMoreGT){for(m=f+1;m<A&&">"!==c[m];m++);m<A?f=m+1:d.noMoreGT=!0}d.noMoreGT&&b.pcdata&&b.pcdata("&lt;?",q,F,g(b,c,f,d,q));break;case ">":b.pcdata&&b.pcdata("&gt;",q,F,g(b,c,f,d,q));break;case "":break;default:b.pcdata&&b.pcdata(h,q,F,g(b,c,f,d,q))}}b.endDoc&&b.endDoc(q)}catch(Ea){if(Ea!==F)throw Ea;}}function V(a){var b=/(<\/|<\!--|<[!?]|[&<>])/g;
a+="";if(U)return a.split(b);for(var c=[],d=0,e;null!==(e=b.exec(a));)c.push(a.substring(d,e.index)),c.push(e[0]),d=e.index+e[0].length;c.push(a.substring(d));return c}function u(a,b,c,d,e,f){var m=t(a,b);if(!m)return a.length;c.endTag&&c.endTag(m.name,d,e,g(c,a,b,f,d));return m.next}function k(a,b,c,d,e,f){b=t(a,b);if(!b)return a.length;c.startTag&&c.startTag(b.name,b.attrs,d,e,g(c,a,b.next,f,d));return b.eflags&ka?p(a,b,c,d,e,f):b.next}function p(b,c,d,e,f,k){var q=b.length;W.hasOwnProperty(c.name)||
(W[c.name]=new RegExp("^"+c.name+"(?:[\\s\\/]|$)","i"));for(var n=W[c.name],m=c.next,x=c.next+1;x<q&&("</"!==b[x-1]||!n.test(b[x]));x++);x<q&&--x;var A=b.slice(m,x).join("");if(c.eflags&a.eflags.CDATA)d.cdata&&d.cdata(A,e,f,g(d,b,x,k,e));else if(c.eflags&a.eflags.RCDATA)d.rcdata&&d.rcdata(l(A),e,f,g(d,b,x,k,e));else throw Error("bug");return x}function t(b,c){var d=/^([-\w:]+)/.exec(b[c]),e={};e.name=d[1].toLowerCase();e.eflags=a.ELEMENTS[e.name];var f=b[c].substr(d[0].length);c+=1;for(var g=b.length;c<
g&&">"!==b[c];c++)f+=b[c];if(!(g<=c)){for(var n=[];""!==f;)if(d=I.exec(f))if(d[4]&&!d[5]||d[6]&&!d[7]){for(var m=d[4]||d[6],k=!1,h=[f,b[c++]];c<g;c++){if(k){if(">"===b[c])break}else 0<=b[c].indexOf(m)&&(k=!0);h.push(b[c])}if(g<=c)break;f=h.join("")}else{var l=d[1].toLowerCase(),r=d[2]?T(d[3]):"";n.push(l,r);f=f.substr(d[0].length)}else f=f.replace(/^[\s\S][^a-z\s]*/,"");e.attrs=n;e.next=c+1;return e}}function T(a){var b=a.charCodeAt(0);if(34===b||39===b)a=a.substr(1,a.length-2);return d(e(a))}function h(b){function c(a,
b){e||b.push(a)}var d,e;return v({startDoc:function(){d=[];e=!1},startTag:function(c,g,n){if(!e&&a.ELEMENTS.hasOwnProperty(c)){var q=a.ELEMENTS[c];if(!(q&a.eflags.FOLDABLE)){var m=b(c,g);if(m){if("object"!==typeof m)throw Error("tagPolicy did not return object (old API?)");if("attribs"in m)g=m.attribs;else throw Error("tagPolicy gave no attribs");var k,h;"tagName"in m?(h=m.tagName,k=a.ELEMENTS[h]):(h=c,k=q);if(q&a.eflags.OPTIONAL_ENDTAG){var l=d[d.length-1];!l||l.orig!==c||l.rep===h&&c===h||n.push("</",
l.rep,">")}q&a.eflags.EMPTY||d.push({orig:c,rep:h});n.push("<",h);for(var r=0,A=g.length;r<A;r+=2){var y=g[r],x=g[r+1];null!==x&&void 0!==x&&n.push(" ",y,'="',f(x),'"')}n.push(">");q&a.eflags.EMPTY&&!(k&a.eflags.EMPTY)&&n.push("</",h,">")}else e=!(q&a.eflags.EMPTY)}}},endTag:function(b,c){if(e)e=!1;else if(a.ELEMENTS.hasOwnProperty(b)){var f=a.ELEMENTS[b];if(!(f&(a.eflags.EMPTY|a.eflags.FOLDABLE))){if(f&a.eflags.OPTIONAL_ENDTAG)for(f=d.length;0<=--f;){var g=d[f].orig;if(g===b)break;if(!(a.ELEMENTS[g]&
a.eflags.OPTIONAL_ENDTAG))return}else for(f=d.length;0<=--f&&d[f].orig!==b;);if(!(0>f)){for(var n=d.length;--n>f;){var m=d[n].rep;a.ELEMENTS[m]&a.eflags.OPTIONAL_ENDTAG||c.push("</",m,">")}f<d.length&&(b=d[f].rep);d.length=f;c.push("</",b,">")}}}},pcdata:c,rcdata:c,cdata:c,endDoc:function(a){for(;d.length;d.length--)a.push("</",d[d.length-1].rep,">")}})}function aa(a,b,c,d,e){if(!e)return null;try{var f=Eb.parse(""+a);if(f&&(!f.hasScheme()||oa.test(f.getScheme()))){var g=e(f,b,c,d);return g?g.toString():
null}}catch(la){}return null}function G(a,b,c,d,e){c||a(b+" removed",{change:"removed",tagName:b});if(d!==e){var f="changed";d&&!e?f="removed":!d&&e&&(f="added");a(b+"."+c+" "+f,{change:f,tagName:b,attribName:c,oldValue:d,newValue:e})}}function K(a,b,c){var d;d=b+"::"+c;if(a.hasOwnProperty(d))return a[d];d="*::"+c;if(a.hasOwnProperty(d))return a[d]}function X(b,c){return K(a.ATTRIBS,b,c)}function ma(b,c){return K(a.LOADERTYPES,b,c)}function ea(b,c){return K(a.URIEFFECTS,b,c)}function fa(b,c,d,e,f){for(var g=
0;g<c.length;g+=2){var k=c[g],h=c[g+1],m=h,l=null,n;if((n=b+"::"+k,a.ATTRIBS.hasOwnProperty(n))||(n="*::"+k,a.ATTRIBS.hasOwnProperty(n)))l=a.ATTRIBS[n];if(null!==l)switch(l){case a.atype.NONE:break;case a.atype.SCRIPT:h=null;f&&G(f,b,k,m,h);break;case a.atype.STYLE:if("undefined"===typeof ga){h=null;f&&G(f,b,k,m,h);break}var r=[];ga(h,{declaration:function(b,c){var e=b.toLowerCase();ia(e,c,d?function(b){return aa(b,a.ueffects.SAME_DOCUMENT,a.ltypes.SANDBOXED,{TYPE:"CSS",CSS_PROP:e},d)}:null);c.length&&
r.push(e+": "+c.join(" "))}});h=0<r.length?r.join(" ; "):null;f&&G(f,b,k,m,h);break;case a.atype.ID:case a.atype.IDREF:case a.atype.IDREFS:case a.atype.GLOBAL_NAME:case a.atype.LOCAL_NAME:case a.atype.CLASSES:h=e?e(h):h;f&&G(f,b,k,m,h);break;case a.atype.URI:h=aa(h,ea(b,k),ma(b,k),{TYPE:"MARKUP",XML_ATTR:k,XML_TAG:b},d);f&&G(f,b,k,m,h);break;case a.atype.URI_FRAGMENT:h&&"#"===h.charAt(0)?(h=h.substring(1),h=e?e(h):h,null!==h&&void 0!==h&&(h="#"+h)):h=null;f&&G(f,b,k,m,h);break;default:h=null,f&&G(f,
b,k,m,h)}else h=null,f&&G(f,b,k,m,h);c[g+1]=h}return c}function ha(b,c,d){return function(e,f){if(a.ELEMENTS[e]&a.eflags.UNSAFE)d&&G(d,e,void 0,void 0,void 0);else return{attribs:fa(e,f,b,c,d)}}}function O(a,b){var c=[];h(b)(a,c);return c.join("")}function na(a,b,c,d){b=ha(b,c,d);return O(a,b)}var ga,ia,wa;"undefined"!==typeof window&&(ga=window.parseCssDeclarations,ia=window.sanitizeCssProperty,wa=window.cssSchema);var ja={lt:"<",LT:"<",gt:">",GT:">",amp:"&",AMP:"&",quot:'"',apos:"'",nbsp:"\u00a0"},
J=/^#(\d+)$/,da=/^#x([0-9A-Fa-f]+)$/,C=/^[A-Za-z][A-Za-z0-9]+$/,Z="undefined"!==typeof window&&window.document?window.document.createElement("textarea"):null,y=/\0/g,N=/&(#[0-9]+|#[xX][0-9A-Fa-f]+|\w+);/g,R=/^(#[0-9]+|#[xX][0-9A-Fa-f]+|\w+);/,r=/&/g,E=/&([^a-z#]|#(?:[^0-9x]|x(?:[^0-9a-f]|$)|$)|$)/gi,H=/[<]/g,M=/>/g,S=/\"/g,I=/^\s*(\[[-.:\w]+\]|[-.:\w]+)(?:\s*(=)\s*((")[^"]*("|$)|(')[^']*('|$)|(?=[a-z][-\w]*\s*=)|[^"'\s]*))?/i,U=3==="a,b".split(/(,)/).length,ka=a.eflags.CDATA|a.eflags.RCDATA,F={},
W={},oa=/^(?:https?|geo|mailto|sms|tel)$/i,D={};D.escapeAttrib=D.escapeAttrib=f;D.makeHtmlSanitizer=D.makeHtmlSanitizer=h;D.makeSaxParser=D.makeSaxParser=v;D.makeTagPolicy=D.makeTagPolicy=ha;D.normalizeRCData=D.normalizeRCData=l;D.sanitize=D.sanitize=na;D.sanitizeAttribs=D.sanitizeAttribs=fa;D.sanitizeWithPolicy=D.sanitizeWithPolicy=O;D.unescapeEntities=D.unescapeEntities=d;return D}(Y);var Gb=ta({br:!0,col:!0,hr:!0,img:!0,input:!0,source:!0,track:!0,wbr:!0,area:!0,base:!0,command:!0,embed:!0,keygen:!0,link:!0,meta:!0,param:!0}),Hb=/^(data-|aria-)|^role$/i,Ib=0;
function Jb(a,b){function c(a){0==f&&d.push(a)}var e=Fb.makeTagPolicy(function(a){return"https"===a.getScheme()?a:null}),d=[],f=0,l=Object.assign({script:!0,svg:!0},mb),v=Fb.makeSaxParser({startTag:function(a,d){if(0<f)Gb[a]||f++;else{for(var g=ua(a,"amp-"),u=[],k=0;k<d.length;k+=2){var p=d[k];p&&"["==p[0]&&"]"==p[p.length-1]&&(d[k]=p.slice(1,-1),u.push(k))}if(l[a])f++;else if(!g){var t=d.slice(0),v=e(a,d);if(v)for(d=v.attribs,k=0;k<d.length;k+=2)p=d[k],ob.includes(p)?d[k+1]=t[k+1]:0==p.search(Hb)?
d[k+1]=t[k+1]:pb[a]&&pb[a].includes(p)&&(d[k+1]=t[k+1]);else f++;if("a"==a){for(var k=-1,h=!1,p=0;p<t.length;p+=2)"target"==t[p]?k=p+1:"href"==t[p]&&(h=null!=d[p+1]);var w=-1!=k?t[k]:null;null!=w?(w=w.toLowerCase(),d[k]=-1!=qb.indexOf(w)?w:"_top"):h&&d.push("target","_top")}}if(0<f)Gb[a]&&f--;else{var G=u.some(function(a){return!!d[a+1]});G&&d.push("i-amphtml-binding","");(G||g)&&b&&d.push("i-amphtml-key",String(Ib++));c("<");c(a);for(g=0;g<d.length;g+=2)if(k=d[g],p=d[g+1],Ab(a,k,p)){c(" ");c(u.includes(g)?
"["+k+"]":k);c('="');if(p){var K=u.includes(g)?p:Bb(a,k,p);c(Fb.escapeAttrib(K))}c('"')}else z().error("sanitizer",'Removing "'+k+'" attribute with invalid '+("value in <"+a+" "+k+'="'+p+'">.'));c(">")}}},endTag:function(a){0<f?f--:(c("</"),c(a),c(">"))},pcdata:c,rcdata:c,cdata:c});v(a);return d.join("")}function Kb(a){return Fb.sanitizeWithPolicy(a,Lb)}
function Lb(a,b){if("template"==a)for(var c=0;c<b.length;c+=2)if("type"==b[c]&&"amp-mustache"==b[c+1])return{tagName:a,attribs:["type","amp-mustache"]};return nb.includes(a)?{tagName:a,attribs:b}:null};/*
 mustache.js - Logic-less {{mustache}} templates with JavaScript
 http://github.com/janl/mustache.js
*/
var Mb={};
(function mustacheFactory(b){function c(b){return"function"===typeof b}function e(b){return h(b)?"array":typeof b}function d(b){return b.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$&")}function f(b,c){return null!=b&&"object"===typeof b&&Object.prototype.hasOwnProperty.call(b,c)}function l(b,c){return aa.call(b,c)}function v(b){return!l(G,b)}function g(b){return String(b).replace(/[&<>"'`=\/]/g,function ia(b){return K[b]})}function w(c,e){function f(){if(C&&!w)for(;t.length;)delete p[t.pop()];else t=
[];w=C=!1}function g(b){"string"===typeof b&&(b=b.split(ma,2));if(!h(b)||2!==b.length)throw Error("Invalid tags: "+b);y=new RegExp(d(b[0])+"\\s*");N=new RegExp("\\s*"+d(b[1]));R=new RegExp("\\s*"+d("}"+b[1]))}if(!c)return[];var l=[],p=[],t=[],C=!1,w=!1,y,N,R;g(e||b.tags);for(var r=new k(c),E,H,M,S,I;!r.eos();){c=r.pos;if(H=r.scanUntil(y)){E=0;for(var U=H.length;E<U;++E)M=H.charAt(E),v(M)?t.push(p.length):w=!0,p.push(["text",M,c,c+1]),c+=1,"\n"===M&&f()}if(!r.scan(y))break;C=!0;E=r.scan(ha)||"name";
r.scan(X);"="===E?(H=r.scanUntil(ea),r.scan(ea),r.scanUntil(N)):"{"===E?(H=r.scanUntil(R),r.scan(fa),r.scanUntil(N),E="&"):H=r.scanUntil(N);if(!r.scan(N))throw Error("Unclosed tag at "+r.pos);S=[E,H,c,r.pos];p.push(S);if("#"===E||"^"===E)l.push(S);else if("/"===E){I=l.pop();if(!I)throw Error('Unopened section "'+H+'" at '+c);if(I[1]!==H)throw Error('Unclosed section "'+I[1]+'" at '+c);}else if("name"===E||"{"===E||"&"===E)w=!0}if(I=l.pop())throw Error('Unclosed section "'+I[1]+'" at '+r.pos);return u(V(p))}
function V(b){for(var c=[],d,e,f=0,g=b.length;f<g;++f)if(d=b[f])"text"===d[0]&&e&&"text"===e[0]?(e[1]+=d[1],e[3]=d[3]):(c.push(d),e=d);return c}function u(b){for(var c=[],d=c,e=[],f,g,h=0,k=b.length;h<k;++h)switch(f=b[h],f[0]){case "#":case "^":d.push(f);e.push(f);d=f[4]=[];break;case "/":g=e.pop();g[5]=f[2];d=0<e.length?e[e.length-1][4]:c;break;default:d.push(f)}return c}function k(b){this.tail=this.string=b;this.pos=0}function p(b,c){this.view=b;this.cache={".":this.view};this.parent=c}function t(){this.cache=
{}}var T=Object.prototype.toString,h=Array.isArray||function ga(b){return"[object Array]"===T.call(b)},aa=RegExp.prototype.test,G=/\S/,K={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;","/":"&#x2F;","`":"&#x60;","=":"&#x3D;"},X=/\s*/,ma=/\s+/,ea=/\s*=/,fa=/\s*\}/,ha=/#|\^|\/|>|\{|&|=|!/;k.prototype.eos=function ia(){return""===this.tail};k.prototype.scan=function wa(b){b=this.tail.match(b);if(!b||0!==b.index)return"";b=b[0];this.tail=this.tail.substring(b.length);this.pos+=b.length;return b};
k.prototype.scanUntil=function ja(b){b=this.tail.search(b);var c;switch(b){case -1:c=this.tail;this.tail="";break;case 0:c="";break;default:c=this.tail.substring(0,b),this.tail=this.tail.substring(b)}this.pos+=c.length;return c};p.prototype.push=function J(b){return new p(b,this)};p.prototype.lookup=function da(b){var d=this.cache,e;if(d.hasOwnProperty(b))e=d[b];else{for(var g=this,h,k,l=!1;g;){if(0<b.indexOf("."))for(e=g.view,h=b.split("."),k=0;null!=e&&k<h.length;){if(!f(e,h[k])){e=null;break}k===
h.length-1&&(l=!0);e=e[h[k++]]}else f(g.view,b)?(e=g.view[b],l=!0):e=null;if(l)break;g=g.parent}d[b]=e}c(e)&&(e=e.call(this.view));return e};t.prototype.clearCache=function C(){this.cache={}};t.prototype.parse=function(b,c){var d=this.cache,e=d[b];null==e&&(e=d[b]=w(b,c));return e};t.prototype.render=function Z(b,c,d){var e=this.parse(b);c=c instanceof p?c:new p(c);return this.renderTokens(e,c,d,b)};t.prototype.renderTokens=function y(b,c,d,e){for(var f="",g,h,k,l=0,r=b.length;l<r;++l)k=void 0,g=
b[l],h=g[0],"#"===h?k=this.renderSection(g,c,d,e):"^"===h?k=this.renderInverted(g,c,d,e):">"===h?k=this.renderPartial(g,c,d,e):"&"===h?k=this.unescapedValue(g,c):"name"===h?k=this.escapedValue(g,c):"text"===h&&(k=this.rawValue(g)),void 0!==k&&(f+=k);return f};t.prototype.renderSection=function N(b,d,e,f){function g(b){return k.render(b,d,e)}var k=this,l="",p=d.lookup(b[1]);if(p){if(h(p))for(var r=0,t=p.length;r<t;++r)l+=this.renderTokens(b[4],d.push(p[r]),e,f);else if("object"===typeof p||"string"===
typeof p||"number"===typeof p)l+=this.renderTokens(b[4],d.push(p),e,f);else if(c(p)){if("string"!==typeof f)throw Error("Cannot use higher-order sections without the original template");p=p.call(d.view,f.slice(b[3],b[5]),g);null!=p&&(l+=p)}else l+=this.renderTokens(b[4],d,e,f);return l}};t.prototype.renderInverted=function R(b,c,d,e){var f=c.lookup(b[1]);if(!f||h(f)&&0===f.length)return this.renderTokens(b[4],c,d,e)};t.prototype.renderPartial=function r(b,d,e){if(e&&(b=c(e)?e(b[1]):e[b[1]],null!=
b))return this.renderTokens(this.parse(b),d,e,b)};t.prototype.unescapedValue=function E(c,d){c=d.lookup(c[1]);if(null!=c)return b.sanitizeUnescaped?b.sanitizeUnescaped(c):c};t.prototype.escapedValue=function H(c,d){c=d.lookup(c[1]);if(null!=c)return b.escape(c)};t.prototype.rawValue=function M(b){return b[1]};b.name="mustache.js";b.version="2.2.0";b.tags=["{{","}}"];var O=new t;b.clearCache=function(){return O.clearCache()};b.parse=function(b,c){return O.parse(b,c)};b.render=function(b,c,d){if("string"!==
typeof b)throw new TypeError('Invalid template! Template should be a "string" but "'+e(b)+'" was given as the first argument for mustache#render(template, view, partials)');return O.render(b,c,d)};b.to_html=function S(d,e,f,g){d=b.render(d,e,f);if(c(g))g(d);else return d};b.escape=g;b.sanitizeUnescaped=null;b.setUnescapedSanitizer=function I(c){b.sanitizeUnescaped=c};b.Scanner=k;b.Context=p;b.Writer=t})(Mb);function Nb(a,b){a=AMP.BaseTemplate.call(this,a,b)||this;Mb.setUnescapedSanitizer(Kb);z().warn("amp-mustache",'The extension "amp-mustache-0.1.js" is deprecated. Please use a more recent version of this extension.');return a}ba(Nb,AMP.BaseTemplate);
Nb.prototype.compileCallback=function(){var a=this;if(!this.viewerCanRenderTemplates()){this.I={};var b=0,c=va(this.element);xa(c.querySelectorAll("template"),function(c){var d="__AMP_NESTED_TEMPLATE_"+b;a.I[d]=c.outerHTML;var e=a.element.ownerDocument.createTextNode("{{{"+d+"}}}");c.parentNode.replaceChild(e,c);b++});var e=this.element.ownerDocument.createElement("div");e.appendChild(c);this.J=e.innerHTML;Mb.parse(this.J)}};
Nb.prototype.render=function(a){var b=a;if(!this.viewerCanRenderTemplates()){var c=a;"object"===typeof a&&(c=Object.assign({},a,this.I));b=Mb.render(this.J,c)}a=this.win.document.createElement("div");var e;var d=self;if(d.__AMP__EXPERIMENT_TOGGLES)e=d.__AMP__EXPERIMENT_TOGGLES;else{d.__AMP__EXPERIMENT_TOGGLES=Object.create(null);e=d.__AMP__EXPERIMENT_TOGGLES;if(d.AMP_CONFIG)for(var f in d.AMP_CONFIG){var l=d.AMP_CONFIG[f];"number"===typeof l&&0<=l&&1>=l&&(e[f]=Math.random()<l)}if(d.AMP_CONFIG&&Array.isArray(d.AMP_CONFIG["allow-doc-opt-in"])&&
0<d.AMP_CONFIG["allow-doc-opt-in"].length&&(f=d.AMP_CONFIG["allow-doc-opt-in"],l=d.document.head.querySelector('meta[name="amp-experiments-opt-in"]')))for(var l=l.getAttribute("content").split(","),v=0;v<l.length;v++)-1!=f.indexOf(l[v])&&(e[l[v]]=!0);Object.assign(e,Ma(d));if(d.AMP_CONFIG&&Array.isArray(d.AMP_CONFIG["allow-url-opt-in"])&&0<d.AMP_CONFIG["allow-url-opt-in"].length)for(f=d.AMP_CONFIG["allow-url-opt-in"],d=ra(d.location.originalHash||d.location.hash),l=0;l<f.length;l++)v=d["e-"+f[l]],
"1"==v&&(e[f[l]]=!0),"0"==v&&(e[f[l]]=!1)}b=Jb(b,!!e["amp-list-diffing"]);a.innerHTML=b;return this.unwrap(a)};AMP.registerTemplate("amp-mustache",Nb);
})});
//# sourceMappingURL=amp-mustache-0.1.js.map

